### ISSUE TITLE
BUG - Database Error in model `stg_tiktok_ads__ad_group_history` for BQ Adapter

### ISSUE THREAD

**Issue by satyam-gupta-ib** [fivetran/dbt_tiktok_ads#15]
**Describe the bug**
While using TikTok Ads Package version= 0.5.0, I am encountering an error while running the model `stg_tiktok_ads__ad_group_history`

Exact Error Message:
```No matching signature for function COALESCE for argument types: JSON, STRING. Supported signature: COALESCE([ANY, ...]) at [211:9]```

**Expected behavior**
The model should run through and build the table without encountering the error.

**Project variables configuration**
```yml
models:
  core:
    +database: data-core
    tiktok_ads:
      +schema: tiktok_ads
    tiktok_ads_source:
      +schema: stg_tiktok_ads

vars:
  tiktok_ads_database: data-lake
  tiktok_ads_schema: tiktok_ads
```

**Package Version**
```yml
packages:
  - package: fivetran/tiktok_ads_source
    version: [">=0.5.0", "<0.6.0"]
```

**Warehouse**

 
- [x] BigQuery
- [ ] Redshift
- [ ] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

![image](https://github.com/fivetran/dbt_tiktok_ads/assets/163649932/3fefec32-5156-4737-85f1-e70b78b421e6)

**Please indicate the level of urgency** 

Quite Urgent as currently I am unable to use the package and hence can't build Ads Report.

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [x] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.
