### ISSUE TITLE
[Bug] Deprecation Warning: Found `freshness` as a top-level property of `tiktok_ads`

### ISSUE THREAD

**Issue by eric-workweek** [fivetran/dbt_tiktok_ads#28]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the issue

While testing upgrading the `dbt_ad_reporting` package to `v1.14.0`, a couple issues came up. One, for a failed test, was resolved by #27. Another is a deprecation warning that was not present in `v1.13.0`. This does not prevent the package and its models from running, but I've been in the process of upgrading our other packages to avoid warnings.

### Relevant error log or model output

```shell
[WARNING]: Deprecated functionality
Found `freshness` as a top-level property of `tiktok_ads` in file
`models/src_tiktok_ads.yml`. The `freshness` top-level property should be moved
into the `config` of `tiktok_ads`.
```

### Expected behavior

No deprecation warnings

### Possible solution

Following the recommendation of the warning

### dbt Project configurations

N/A

### Package versions

```
# we recommend using ranges to capture non-breaking changes automatically
packages:
...
  - package: fivetran/ad_reporting
    version: [">=1.14.0", "<1.15.0"]
```

### What database are you using dbt with?

bigquery

### How are you running this dbt package?

dbt Cloud™

### dbt Version

Latest

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance.
- [x] No.
